### ISSUE TITLE
is this a virus?

### ISSUE THREAD

**Issue by trademarkman** [fcFn/traymond#32]
i scanned it with virustotal and saw it had multiple viruses

**Comment by fcFn** [comment]
Hi, @trademarkman. I scan it too just now. Here's [the report](https://www.virustotal.com/gui/file/4c87f96849d38d083199316a5afdd6e9cc1206825a1fcbcd00e5150a6e808a23).

A few, though not the smallest number, of unfamiliar scanners do flag it as a *possible* virus. Most likely due to the app invasive, though by design, nature: it has to read window data to be able to put them into the tray. Most certainly I did not intentionally put any virus into the binary. 

However, the safest option to proceed would be to use the source files to build the app yourself. I would appreciate that if you did so, you scan the resulting binary on Virustotal and post your report here.

**Comment by trademarkman** [comment]
Awesome, thank you so much!
