### ISSUE TITLE
Doesn't Work With Task Bar Button

### ISSUE THREAD

**Issue by Riajyuu** [fcFn/traymond#5]
Environ: Windows 10.16299.125 Pro

STR:
1. run Traymond & Any other app
1. pin the app to the task bar
1. use `Win` + `Shift` + `Z` to minimize the app
1. click the task bar icon 

Actual Results:
1. the app window is restored but `Win` + `Shift` + `Z` does not work any more
1. the app tray icon remains on Windows tray area. Double click on it to make it disappear and `Win` + `Shift` + `Z` works again.

Expected Results:
- when the task bar button is click, `Win` + `Shift` + `Z` should have minimized the window as well and the tray icon should have disappeared

**Comment by fcFn** [comment]
@Riajyuu I believe this is fixed in the latest release I just shipped (**v1.0.4**). Sorry for taking so long.

The only thing we, I think, cannot do here, is destroy the tray icon when you maximize the app back by clicking on the task bar button, because the result of clicking the pinned app button varies across applications. Some allow multiple instances and you might want to have some of them minimized to tray icon and some not (i.e. [Hyper](https://hyper.is/)). Thunderbird only runs as a single instance, so the tray icon will always remain once you have minimized it unless you double click it yourself. But the fix should now allow to use the minimizing hotkey without doing that.

Please reopen the issue if the problem remains.
